---
title: "Reproducible document"
author: "Sarah C. Sentis"
format: html
---

## Basics of R

```{r}
1 + 1 
```
## Setup code chunk 

```{r setup}
#| message: false 
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(
#csv2 for ; csv for comma; when underscore e.g. in read_csv, then it is from tidyverse 
here::here("data/post-meal-insulin.csv")
)
```

## Showing the data 
```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```

```{r}
ggplot(post_meal_data, aes(x = BMI)) + 
  geom_histogram()
```
```{r}
#| fig-cap: "Distribution BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) + 
  geom_histogram()
```

@fig-bmi-histo


## Exercise: discrete plots 

```{r}
#| fig-cap: "Glykemi Bar-Plot"
#| label: fig-glykemi-bar
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```
@fig-glykemi-bar 




```{r}
post_meal_data |> 
  ggplot(aes(x = Group, fill = glykemi)) + 
  geom_bar()
```

```{r}
post_meal_data |> 
  ggplot(aes(x = Group, fill = as.character(glykemi))) + 
  geom_bar()
```

```{r}
post_meal_data |> 
  ggplot(aes(x = Group, fill = as.character(glykemi))) + 
  geom_bar(position = position_dodge())
```

## Putting two plots side by side 

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

```{r side-by-side figures}
#| fig-cap: "BMI and glycemia, side by side"
#| label: fig-bmi-glykemi
#| fig-subcap: 
#| - "Distribution of BMI"
#| - "Number of those with glycemia"
#| layout-ncol: 2

ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```



## About me 
- Name: Sarah Sentis 
- Affiliation: University of Southern Denmark 

I am a **Postdoc** and work at the institute of *Biochemistry and Molecular Biology*.
---

## Simple code
```{r}
3*3
```

## Testing for Git 
It is raining today and the sun is not shining. 


